//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangout.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangout.Client.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t amplify this buzz at this time. Please try again later. .
        /// </summary>
        internal static string CannotAmplify {
            get {
                return ResourceManager.GetString("CannotAmplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t de-amplify this buzz at this time. Please try again later..
        /// </summary>
        internal static string CannotDeamplify {
            get {
                return ResourceManager.GetString("CannotDeamplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t like this buzzat this time. Please try again later..
        /// </summary>
        internal static string CannotLike {
            get {
                return ResourceManager.GetString("CannotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t undo amplification this buzz to at this time. Please try again later..
        /// </summary>
        internal static string CannotUnAmplify {
            get {
                return ResourceManager.GetString("CannotUnAmplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t undo de-amplification this buzz to at this time. Please try again later..
        /// </summary>
        internal static string CannotUnDeAmplify {
            get {
                return ResourceManager.GetString("CannotUnDeAmplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t un-like this buzz at this time. Please try again later..
        /// </summary>
        internal static string CannotUnLike {
            get {
                return ResourceManager.GetString("CannotUnLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t follow at this time. Please try again later..
        /// </summary>
        internal static string CantFollow {
            get {
                return ResourceManager.GetString("CantFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t unfollow at this time. Please try again later..
        /// </summary>
        internal static string CantUnfollow {
            get {
                return ResourceManager.GetString("CantUnfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re loading categories. .
        /// </summary>
        internal static string CategoriesLoading {
            get {
                return ResourceManager.GetString("CategoriesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. We cant share this buzz to Facebook at this time. .
        /// </summary>
        internal static string FacebookStatusError {
            get {
                return ResourceManager.GetString("FacebookStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Frst Launch of the App. Do you want to see a tutorial of how to use the application?
        ///
        ///Click Ok to see tutorial. To browse through the tutorial tap the screen..
        /// </summary>
        internal static string FirstStartMessage {
            get {
                return ResourceManager.GetString("FirstStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy &amp; Terms.
        /// </summary>
        internal static string PrivacyPolicyCaption {
            get {
                return ResourceManager.GetString("PrivacyPolicyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We collect some of your personal information like your email address, name, and even your location.  The application uses the location service to find points of interest near you. We respect your privacy and We don&apos;t sell any of your personal information to any third party. To serve you better we will use your device location services to find new shout-outs/hangouts near you and also for suggesting you interested people around. However the location information shall not be released to any third party organi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. We cant share this buzz to Twitter at this time..
        /// </summary>
        internal static string TwitterStatusError {
            get {
                return ResourceManager.GetString("TwitterStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. Its windy up there and We can&apos;t connect to Zoik it!.
        /// </summary>
        internal static string Windy {
            get {
                return ResourceManager.GetString("Windy", resourceCulture);
            }
        }
    }
}
