//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangout.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangout.Web.MailTexts", typeof(MailTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey &lt;USER&gt;,
        ///
        ///Forgot your password? No problem! We have a new one for you. 
        ///
        ///Your new password : &lt;PASSWORD&gt;
        ///
        ///If you still cant login to your account with this new password. Do write us back and We&apos;d love to help you out. 
        ///
        ///Happy Zoiking!
        ///
        ///Thank you. 
        ///
        ///Regards,
        ///Zoik it Support Team..
        /// </summary>
        internal static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password. .
        /// </summary>
        internal static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey &lt;USER&gt;,
        ///
        ///Your password has been changed to a new password. 
        ///
        ///If you havent changed your password, then reply to this email immediately. 
        ///
        ///If you cant login to your account with this new password. Do write us back and We&apos;d love to help you out. 
        ///
        ///Happy Zoiking!
        ///
        ///Thank you. 
        ///
        ///Regards,
        ///Zoik it Support Team..
        /// </summary>
        internal static string PasswordChangeBody {
            get {
                return ResourceManager.GetString("PasswordChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. .
        /// </summary>
        internal static string PasswordChangeSubject {
            get {
                return ResourceManager.GetString("PasswordChangeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey &lt;USER&gt;,
        ///
        ///Thank you for registering to Zoik it!
        ///
        ///So, what&apos;s next?  
        ///
        ///You&apos;re free to discover people around who like what you like. Discover people, follow them and get notified when someone interesting is on a visit. Well You can even discover buzz around your city. Do let us know if you find something interesting! 
        ///
        ///If you havent registered and you believe this email dropped in your inbox by mistake. Please do reply immediately and let us know about it.
        ///
        ///One last thing, We need to verify your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrationMailBody {
            get {
                return ResourceManager.GetString("RegistrationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering..
        /// </summary>
        internal static string RegistrationMailSubject {
            get {
                return ResourceManager.GetString("RegistrationMailSubject", resourceCulture);
            }
        }
    }
}
